version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing dependencies...
      - cd lambda
      - npm install || echo "No dependencies to install"
  
  pre_build:
    commands:
      - echo Pre-build phase...
      
      # List the contents of the current directory to verify where you are
      - echo "Listing the files in the current directory for debugging..."
      - cd ..
      - ls -al  # This will list all files in the current directory
      
      # If scripts folder exists, list its contents
      - echo "Checking if 'scripts' folder exists"
      - ls -al ./scripts  # This will list contents in 'scripts' folder if it exists

      # Check if the file is present, and then make it executable
      - echo "Trying to chmod the script"
      - sudo chmod +x ./scripts/check_env_vars.sh  # Ensure the script is executable (update path)
      
      # Call the script to check for required environment variables
      - echo "Running check_env_vars.sh"
      - . ./scripts/check_env_vars.sh  # Source the script to check for required environment variables
  
  build:
    commands:
      - echo Build phase...
      - sudo chmod +x ./scripts/deploy.sh  # Ensure the deploy script is executable
      - . ./scripts/deploy.sh  # Source the deploy script
       - zip -r lambda.zip .  # Create lambda.zip in the current directory

artifacts:
  files:
    - lambda.zip  # Ensure the file name matches the one created during the build phase

cache:
  paths:
    - node_modules/**/*  # Cache node modules to speed up future builds