version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing dependencies...
      - cd lambda
      - npm install || echo "No dependencies to install"
  
  pre_build:
    commands:
      - echo Pre-build phase...
      
      - echo "Listing the files in the current directory for debugging..."
      - cd ..
      - ls -al  
      
      - echo "Checking if 'scripts' folder exists"
      - ls -al ./scripts 

      - echo "Trying to chmod the script"
      - sudo chmod +x ./scripts/check_env_vars.sh 
      
      - echo "Running check_env_vars.sh"
      - . ./scripts/check_env_vars.sh 
  
  build:
    commands:
      - echo Build phase...
      - sudo chmod +x ./scripts/deploy.sh  
      - . ./scripts/deploy.sh  
      - zip -r lambda.zip .  

artifacts:
  files:
    - lambda.zip
    - template.yaml
cache:
  paths:
    - node_modules/**/*  