version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      # Install dependencies (if any)
      - echo Installing dependencies...
      - cd lambda
      - npm install || echo "No dependencies to install"
  
  pre_build:
    commands:
      - echo Pre-build phase...
      - chmod +x ./check_env_vars.sh 
      - . check_env_vars.sh  
  
  build:
    commands:
      - echo Build phase...
      - chmod +x ../deploy.sh  
      - . deploy.sh  
      - zip -r ../lambda.zip .  
  
artifacts:
  files:
    - lambda.zip  # This will be the artifact if needed for Lambda function update (optional)
  
cache:
  paths:
    - node_modules/**/*  # Cache node modules to speed up future builds
