version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      # Install dependencies (if any)
      echo Installing dependencies...
      cd lambda
      npm install || echo "No dependencies to install"
  
  pre_build:
    commands:
      echo Pre-build phase...
  
  build:
    commands:
      echo Build phase...
      # Create a package for Lambda (optional if you want to zip the function code)
      zip -r ../lambda.zip .
  
  post_build:
    commands:
      echo Post-build phase...
      # Make the deploy.sh script executable and deploy the Lambda function
      chmod +x ../deploy.sh
      ./deploy.sh

artifacts:
  files:
    - lambda.zip  # This will be the artifact if needed for Lambda function update (optional)
  
cache:
  paths:
    - node_modules/**/*  # Cache node modules to speed up future builds

    VAR1: "Value for VAR1"
    VAR2: "Value for VAR2"
    VAR3: "Value for VAR3"