version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      # Install dependencies (if any)
      - echo Installing dependencies...
      - cd lambda
      - npm install || echo "No dependencies to install"
  
  pre_build:
    commands:
      - echo Pre-build phase...
      - sudo chmod 777 ./check_env_vars.sh  # Ensure the script is executable
      - . check_env_vars.sh  # Call the script to check for required environment variables
  
  build:
    commands:
      - echo Build phase...
      - sudo chmod 777 ./deploy.sh  # Ensure the deploy script is executable
      - . deploy.sh  # Call the deploy script
      - zip -r ../lambda.zip .  # Optionally zip the lambda code
  
artifacts:
  files:
    - lambda.zip  # This will be the artifact if needed for Lambda function update (optional)
  
cache:
  paths:
    - node_modules/**/*  # Cache node modules to speed up future builds
