version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      # Install dependencies (if any)
      - echo Installing dependencies...
      - cd lambda
      - npm install || echo "No dependencies to install"
  
  pre_build:
    commands:
      - echo Pre-build phase...
      - echo "Listing the files in the current directory for debugging..."
      - ls -a  # List contents of the current directory to verify script location
      - echo "Listing the contents of the 'scripts' directory..."
      - ls -a ./scripts  # List contents of the 'scripts' folder (if it's in a subdirectory)
      - chmod +x ./scripts/check_env_vars.sh  # Ensure the script is executable (update path)
      - . ./scripts/check_env_vars.sh  # Source the script to check for required environment variables
  
  build:
    commands:
      - echo Build phase...
      - chmod +x ./scripts/deploy.sh  # Ensure the deploy script is executable
      - . ./scripts/deploy.sh  # Source the deploy script
      - zip -r ../lambda.zip .  # Optionally zip the lambda code
  
artifacts:
  files:
    - lambda.zip  # This will be the artifact if needed for Lambda function update (optional)
  
cache:
  paths:
    - node_modules/**/*  # Cache node modules to speed up future builds
